ktor:
  deployment:
    port: 8080

# 服务器host, 该项决定了CORS策略中的允许请求地址
# 允许使用通配符例如*.tachyon.moe
serverHost:
  - '*.tachyon.moe'
database:
  # 数据库实现, 可选值: sql
  impl: sql
  sql:

    # 支持的数据库：
    # - Postgres

    #数据库用户名
    user: 'YourSqlUser'
    #数据库密码
    password: 'YourSqlPassword'

    # 数据库连接地址
    url: 'jdbc:postgresql://YourSqlHost:YourSqlPort/YourDatabaseName' # postgres

    # 数据库驱动 该项可以不填或填为null以通过url自动识别对应驱动
    driver: null
    ## driver: 'com.impossibl.postgres.jdbc.PGDriver' # postgres

    # 数据库懒惰初始化
    lazyInit: true
maxImageSize: 10485760 # 10MB